version: "3"

services:
    nginx:
      image: nginx:latest
      volumes:
        - ./docker/nginx/:/etc/nginx/conf.d/
        - ./html:/html
      ports:
        - "80:80"

    php:
      image: php:7-fpm
      volumes:
        - ./html:/html

    db:
      image: mysql:latest
      volumes:
        - ./docker/db:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=local
        - MYSQL_USER=local
        - MYSQL_PASSWORD=local
      ports:
        - "3306:3306"

    phpmyadmin:
      image: phpmyadmin/phpmyadmin:latest
      environment:
        - PMA_HOST=db
        - PMA_USER=local
        - PMA_PASSWORD=local
      volumes:
        - /sessions
