version: "3"

services:
    nginx:
      image: nginx
      volumes:
        - ./docker/nginx/:/etc/nginx/conf.d/
        - ./html:/html
      ports:
        - "80:80"
      depends_on:
        - phpmyadmin

    php:
      build: ./docker/php
      volumes:
        - ./html:/html
        - ./docker/php/php.ini:/usr/local/etc/php/php.ini

    db:
      image: mariadb
      volumes:
        - ./docker/db:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=local
        - MYSQL_USER=local
        - MYSQL_PASSWORD=local

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      environment:
        - PMA_HOST=db
        - PMA_USER=local
        - PMA_PASSWORD=local
      volumes:
        - /sessions
      depends_on:
        - db
